### ISSUE TITLE
Getting traversal on remote graph breaks with Gremlin 3.2.0 (NoSuchMethodError)

### ISSUE THREAD

**Issue by chrimobs** [thinkaurelius/titan#1319]
I use Titan with DynamoDB as storage backend. 
I used to have a traverser [g] ready to use after starting Gremlin server. I changed to the 3.2.0 version of the Gremlin stack and [g] is no longer instantiated on startup. A request like
`:> graph.traversal().V()` now fails with the following stack trace:

`203486 [gremlin-server-exec-1] WARN  org.apache.tinkerpop.gremlin.server.op.AbstractEvalOpProcessor  - Exception processing a script on request [RequestMessage{, requestId=f4b80cd8-d406-4883-9e01-6fa2637594db, op='eval', processor='', args={gremlin=graph.traversal().V(), bindings={}, batchSize=64}}].
java.lang.NoSuchMethodError: org.apache.tinkerpop.gremlin.process.traversal.Traversal$Admin.getEngine()Lorg/apache/tinkerpop/gremlin/process/traversal/TraversalEngine;
    at com.thinkaurelius.titan.graphdb.tinkerpop.optimize.TitanLocalQueryOptimizerStrategy.apply(TitanLocalQueryOptimizerStrategy.java:40)
    at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversalStrategies.applyStrategies(DefaultTraversalStrategies.java:79)
    at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.applyStrategies(DefaultTraversal.java:92)
    at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:145)
    at org.apache.tinkerpop.gremlin.server.op.AbstractOpProcessor.handleIterator(AbstractOpProcessor.java:81)
    at org.apache.tinkerpop.gremlin.server.op.AbstractEvalOpProcessor.lambda$evalOpInternal$3(AbstractEvalOpProcessor.java:207)
    at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:272)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
`

Libraries I use:
- com.thinkaurelius-titan:titan-core:1.0.0
- org.apache.tinkerpop.gremlin:gremlin-core:3.2.0-incubating

**Comment by spmallette** [comment]
Those versions are not compatible.Titan 1.0.0 works with TinkerPop 3.0.x. There is a branch of development on titan11 for 3.1.x support and then PR #1312 for 3.2.x support. Not sure where the dynamo implementation is on that.
